In [1]:
import numpy as np
import xml.etree.ElementTree as ET

In [2]:
# Aircraft code
headers=['aircraft_id', 125, 250, 500, 750, 1000, 1500, 2000, 2500, 3000, 3500, 4000, 4500,\
            5000, 5500, 6000, 7000, 8000, 85000]
data_1 = ['fokker 100', 1296, 2703, 3788, 5129, 6427, 8937, 13757, 16104]
data_2 = ['bae 146-100', 1289, 2754, 3874, 5258, 6600, 9199]
data_3 = ['bae 146-200', 1289, 2754, 3874, 5258, 6600, 9199, 11725]
data_4 = ['bae 146-300', 1324, 2874, 4105, 5621, 7100, 9986]
data_5 = ['bae 146-all', 1289, 2754, 3874, 5258, 6600, 9199, 11725]
data_6 = ['airbus a310', 2628, 5537, 7790, 10759, 13658, 19323, 24876, 30356, 35784, 41172, 46530, 51862, 57175]
data_7 = ['airbus a310-300', 2628, 5537, 7790, 10759,  13658, 19323, 24876, 30356, 35784, 41172, 46530, 51862, 57175]
data_8 = ['airbus a318', 1488, 3016, 3925, 5234, 6482, 8931, 11335, 13729, 16130]
data_9 = ['airbus a319', 1596, 3259, 4323, 5830, 7271, 10026, 12668, 15233, 17741, 20203]
data_10 = ['airbus a320-100/200', 1672, 3430, 4585, 6212, 7772, 10766, 13648, 16452]
data_11 = ['airbus a321-100/200', 1909, 3925, 5270, 7157, 8970, 12456, 15818, 19094, 22308]
data_12 = ['airbus a330', 3497, 7277, 9980, 13579, 17055, 23769, 30276, 36642, 42903, 49082, 54788, 59831, 64719, 69463, 74074, 78560, 82928]
data_13 = ['airbus a330-200', 3395, 6964, 9550, 12994, 16321, 22747, 28973, 35065, 41057, 46970, 52422, 57231, 61889, 66406, 70793, 75058, 79207]
data_14 = ['airbus a330-300', 3497, 7277, 9980, 13579, 17055, 23769, 30276, 36642, 42903, 49082, 54788, 59831, 64719, 69463]
data_15 = ['airbus a340', 4205, 8452, 11054, 14688, 18192, 24999, 31691, 38363, 45066, 51831, 58678, 65621, 72666, 79169, 85687, 89019, 91982, 94586, 96840, 98752]
data_16 = ['airbus a340-200', 3972, 7985, 10445, 13882, 17198, 23642, 29984, 36312, 42673, 49097, 55603, 62203, 68908, 75453, 80921, 84023, 86770, 89174]
data_17 = ['airbus a340-300', 4205, 8452, 11054, 14688, 18192, 24999, 31691, 38363, 45066, 51831, 58678, 65621, 72666, 79169, 85687, 89019, 91982]
data_18 = ['airbus a340-500', 4456, 9441, 13137, 18027, 22779, 32019, 41031, 49891, 58640, 67304, 75900, 84439, 92931, 101383, 109799, 117578, 124601, 131512, 138319, 145026]
data_10 = ['airbus a340-600', 4778, 10030, 14053, 19362, 24537, 34630, 44505, 54236, 63863, 73412, 82899, 92334, 101727, 111211, 119071, 126796, 134395, 141877]
data_11 = ['airbus a380', 5851, 12016, 17623, 24940, 32211, 46695, 61160, 75638, 90143, 104681, 119255, 133865, 148512, 163196, 177916, 192517, 203465, 214166, 224632]
data_12 = ['airbus a380-F', 5851, 12016, 17623, 24940, 32211, 46695, 61160, 75638, 90143, 104681, 119255, 133865, 148512, 163196, 177916, 192517, 203465, 214166, 224632]

data_13 = ['boeing 717', 1513, 3121, 4235, 5628, 6989, 9646, 12209] 
data_14 = ['boeing 727', 2870, 5891, 7884, 10688, 13379, 18544, 23517, 28361, 33106]
data_15 = ['boeing 737-100', 1695, 3439, 4515, 6053, 7517, 10304, 12964, 15537, 18047, 20504, 22920]
data_16 = ['boeing 737-200', 1778, 3708, 4962, 6727, 8421, 11672, 14802, 17850, 20838, 23777, 26676]
data_17 = ['boeing 737-300', 1616, 3323, 4462, 6061, 7597, 10551, 13400, 16176, 18900, 21582, 24229]
data_18 = ['boeing 737-400', 1685, 3482, 4707, 6419, 8069, 11250, 14328, 17335, 20289, 23203, 26084]
data_19 = ['boeing 737-500', 1539, 3153, 4207, 5694, 7119, 9850, 12477, 15033, 17535, 19995, 22421]
data_20 = ['boeing 737-600', 1525, 3074, 3995, 5324, 6584, 8971, 11239, 13426, 15553, 17631, 19670]
data_21 = ['boeing 737', 1695, 3439, 4515, 6053, 7517, 10304, 12964, 15537, 18047, 20504, 22920]
data_22 = ['boeing 737-800', 1715, 3494, 4621, 6221, 7749, 10666, 13460, 16170, 18818, 21415, 23972]
data_23 = ['boeing 737-900', 1782, 3641, 4839, 6533, 8154, 11255, 14233, 17125, 19954, 22733, 25471]
data_24 = ['boeing 747-400', 4719, 9690, 14212, 20113, 25977, 37657, 49323, 60999, 72696, 84420, 96173, 107956, 119768, 131607, 140292, 148734, 156946, 164938] 
data_25 = ['boeing 747', 4719, 9690, 14212, 20113, 25977, 37657, 49323, 60999, 72696, 84420, 96173, 107956, 119768, 131607, 140292, 148734, 156946, 164938] 
data_26 = ['boeing 757-200', 2159, 4435, 5939, 8054, 10085, 13984, 17740, 21398, 24983, 28159]
data_27 = ['boeing 757-300', 2331, 4825, 6525, 8899, 11188, 15602, 19872, 24044, 28145, 31754]
data_28 = ['boeing 757', 2159, 4435, 5939, 8054, 10085, 13984, 17740, 21398, 24983, 28159]
data_29 = ['boeing 767-200', 2685, 5457, 7625, 10488, 13276, 18707, 24013, 29237, 34402, 39522, 44605, 49659, 54687, 59395, 62791, 66006]
data_30 = ['boeing 767-300', 2900, 5799, 7971, 10965, 13879, 19557, 25104, 30566, 35966, 41318, 46632, 51915, 57172, 62106, 65700, 69112]
data_31 = ['boeing 767-400', 2963, 6129, 8564, 11780, 14911, 21011, 26971, 32839, 38641, 44391, 50100, 55777, 60999, 65000]
data_32 = ['boeing 767', 2900, 5799, 7971, 10965, 13879, 19557, 25104, 30566, 35966, 41318, 46632, 51915, 57172, 62106, 65700, 69112]
data_33 = ['boeing 777-200', 3691, 7819, 10880, 14930, 18866, 26518, 33982, 41320, 48566, 55742, 62861, 69933, 76966, 83966, 90378, 96168, 101853, 107440]
data_34 = ['boeing 777-300', 4084, 8572, 12011, 16549, 20972, 29598, 38038, 46355, 54584, 62745, 70853, 78747, 85475, 92061, 98519, 104857, 111085, 117210, 123237]
data_35 = ['boeing 777', 3691, 7819, 10880, 14930, 18866, 26518, 33982, 41320, 48566, 55742, 62861, 69933, 76966, 83966, 90378, 96168, 101853, 107440, 112934, 118340]
data_36 = ['boeing 787', 2638, 5517, 7708, 10603, 13421, 18911, 24276, 29557, 34779, 39954, 45093, 50202, 55286, 60348, 65392, 70419, 75433, 78744, 81828]
data_37 = ['boeing 787-8', 2638, 5517, 7708, 10603, 13421, 18911, 24276, 29557, 34779, 39954, 45093, 50202, 55286, 60348, 65392, 70419, 75433, 81221, 84439]

Data = [data_1, data_2, data_3, data_4, data_5, data_6, data_7, data_8, data_9, data_10, \
       data_11, data_12, data_13, data_14, data_15, data_16, data_17, data_18, data_19, \
       data_20, data_21, data_22, data_23, data_24, data_25, data_26, data_27, data_28, data_29, data_30, \
       data_31, data_32, data_33, data_34, data_35, data_36, data_37]

In [3]:
values = ET.Element('data')
for i in range(0, len(Data)):
    items = ET.SubElement(values, 'aircraft')
    for j in range(0, len(headers)):
        if j < len(Data[i]):
            if j > 0:
                header_to_use = 'miles_'+str(headers[j])
            else:
                header_to_use = str(headers[j])
            items.set(header_to_use, str( Data[i][j] ) )
        else:
            header_to_use = 'miles_'+str(headers[j])
            items.set(header_to_use, str() )
    del items
    
myfile = open('fuel.xml', 'w')
myfile.write( (ET.tostring(values, encoding='utf8').decode('utf8')) )
myfile.close()